#!/bin/bash
# generate-fpm-patch - Generate a patch file from fpm sources
# 

START_DIR=`pwd`
CONFIGURE_AC="php-fpm/configure.ac"
if [ ! -f "$CONFIGURE_AC" ]; then
	echo This command must be executed one directory ABOVE the
	echo php-fpm source tree, with `php-fpm/generate-fpm-patch`
fi
PKG_DESCR=`cat "$CONFIGURE_AC" | grep AC_INIT | sed -e "s/AC_INIT.//" -e "s/. *$//"`
FPM_PATCH_HEADER=`cat <<- \
	FPM_PATCH_HEADER
	#
	# Ubuntu: https://bugs.launchpad.net/bugs/397721
	# Patch: https://code.launchpad.net/php-fpm
	# Description: $PKG_DESCR
	#
	FPM_PATCH_HEADER
	`
echo "$FPM_PATCH_HEADER" > fpm.patch

mkdir -p php-5.2.10-vanilla/sapi
mkdir -p php-5.2.10/sapi
cd php-5.2.10
cp -Rf ../php-fpm sapi/fpm
cd sapi/fpm

# Remove non-project files
rm -Rf .bzr* .git* *.cache autotools man1
rm -Rf libevent/autotools libevent/*.cache

# Remove those standalone files here that php-src won't use
# rm -rf file1 file2 file3...

cd "$START_DIR"
diff -Naur php-5.2.10-vanilla php-5.2.10 | filterdiff --remove-timestamps >> fpm.patch
patch --quiet --no-backup-if-mismatch -p1 < php-fpm/ac_cr.patch
rm -Rf php-5.2.10-vanilla php-5.2.10
